import { Stack, useRouter } from 'expo-router';
import { Controller, useForm } from 'react-hook-form';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';

import { useTransactionsStore } from '@/src/features/transactions/store/transactions-store';
import { colors } from '@/src/shared/theme/colors';

type ExpenseForm = { title: string; category: string; amount: string };

export default function ExpenseNewScreen() {
  const router = useRouter();
  const setTransactions = useTransactionsStore((state) => state.setTransactions);
  const transactions = useTransactionsStore((state) => state.transactions);
  const { control, formState: { errors }, handleSubmit } = useForm<ExpenseForm>({ defaultValues: { title: '', category: 'Casa', amount: '' } });
  const onSubmit = ({ title, category, amount }: ExpenseForm) => { const amountCents = Math.round(Number(amount.replace(',', '.')) * 100); setTransactions([{ id: `expense-${Date.now()}`, accountId: 'main-account', title: title.trim(), category, amountCents: -Math.abs(amountCents), occurredAt: new Date().toISOString(), syncStatus: 'pending' }, ...transactions]); router.back(); };
  return <ScrollView contentInsetAdjustmentBehavior="automatic" contentContainerStyle={styles.screen}><Stack.Screen options={{ title: 'Nova despesa', presentation: 'modal' }} /><Pressable onPress={() => router.back()} style={styles.back}><Text style={styles.backText}>‹</Text></Pressable><Text style={styles.eyebrow}>NOVA DESPESA</Text><Text style={styles.title}>Registre um gasto</Text><Text style={styles.description}>Tenha clareza sobre para onde o dinheiro da família está indo.</Text><Controller control={control} name="amount" rules={{ required: 'Informe o valor.', pattern: { value: /^\d+(?:[,.]\d{1,2})?$/, message: 'Informe um valor válido.' } }} render={({ field: { onChange, value } }) => <View style={styles.amountBox}><Text style={styles.amountLabel}>Valor da despesa</Text><TextInput autoFocus keyboardType="decimal-pad" placeholder="R$ 0,00" placeholderTextColor={colors.mutedLight} style={styles.amountInput} value={value} onChangeText={onChange} /><Text style={styles.error}>{errors.amount?.message}</Text></View>} /><Controller control={control} name="title" rules={{ required: 'Informe uma descrição.' }} render={({ field: { onChange, value } }) => <Input label="Descrição" placeholder="Ex.: Mercado" value={value} onChangeText={onChange} error={errors.title?.message} />} /><Controller control={control} name="category" render={({ field: { onChange, value } }) => <Input label="Categoria" placeholder="Ex.: Alimentação" value={value} onChangeText={onChange} />} /><Pressable onPress={handleSubmit(onSubmit)} style={styles.primary}><Text style={styles.primaryText}>Salvar despesa</Text><Text style={styles.arrow}>→</Text></Pressable></ScrollView>;
}
function Input({ label, placeholder, value, onChangeText, error }: { label: string; placeholder: string; value: string; onChangeText: (value: string) => void; error?: string }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput placeholder={placeholder} placeholderTextColor={colors.mutedLight} style={[styles.input, error && styles.inputError]} value={value} onChangeText={onChangeText} /><Text style={styles.error}>{error}</Text></View>; }
const styles = StyleSheet.create({ screen: { backgroundColor: colors.background, flexGrow: 1, gap: 14, padding: 20, paddingBottom: 32 }, back: { alignItems: 'center', backgroundColor: colors.surfaceMuted, borderRadius: 22, height: 42, justifyContent: 'center', width: 42 }, backText: { color: colors.text, fontSize: 30, lineHeight: 30 }, eyebrow: { color: colors.muted, fontSize: 12, fontWeight: '900', letterSpacing: 1.2, marginTop: 18 }, title: { color: colors.text, fontSize: 32, fontWeight: '900' }, description: { color: colors.muted, fontSize: 15, lineHeight: 21, marginBottom: 12 }, amountBox: { backgroundColor: colors.surface, borderColor: colors.accent, borderRadius: 20, borderWidth: 2, gap: 6, padding: 18 }, amountLabel: { color: colors.muted, fontSize: 13, fontWeight: '800' }, amountInput: { color: colors.text, fontSize: 32, fontWeight: '900', padding: 0 }, field: { gap: 6 }, label: { color: colors.text, fontSize: 13, fontWeight: '800' }, input: { borderColor: colors.border, borderRadius: 14, borderWidth: 1, color: colors.text, fontSize: 16, minHeight: 56, paddingHorizontal: 16 }, inputError: { borderColor: colors.negative }, error: { color: colors.negative, fontSize: 12, minHeight: 14 }, primary: { alignItems: 'center', backgroundColor: colors.accent, borderRadius: 16, flexDirection: 'row', gap: 12, justifyContent: 'center', marginTop: 12, minHeight: 58 }, primaryText: { color: colors.text, fontSize: 16, fontWeight: '900' }, arrow: { color: colors.text, fontSize: 20, fontWeight: '900' } });
